apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: simplejob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: simplejob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: hello:latest
              imagePullPolicy: IfNotPresent
              name: simplejob
              resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}